#!/bin/sh
# Codespaces location: /workspaces/.codespaces/.persistedshare/dotfiles/codespaces-post-start
# execution log: /workspaces/.codespaces/.persistedshare/creation.log
# testing:
# gh cs create --status --repo github/github
# gh cs list
# gh cs list | tail -n 1 | cut -f 1 | xargs gh cs delete -c

SELFDIR=$(cd "$(dirname "$0")"; pwd)

$SELFDIR/set-petname

# Install tmux config
cp $SELFDIR/.tmux.conf ~/

cp $SELFDIR/.bashrc-additions ~/
cp $SELFDIR/update-vscode-settings ~/
cp $SELFDIR/update-vscode-settings.js ~/

# Source additions from ~/.bashrc
if grep -q "source ~/.bashrc-additions" ~/.bashrc
then
  echo "~/.bashrc already updated"
else
  echo "Adding bashrc additions to ~/.bashrc"
  echo >> ~/.bashrc
  echo "source ~/.bashrc-additions" >> ~/.bashrc
fi
