#!/bin/sh
# Codespaces location: /workspaces/.codespaces/.persistedshare/dotfiles/codespaces-post-start

SELFDIR=$(cd "$(dirname "$0")"; pwd)

# Install packages here
# See https://github.com/MikeMcQuaid/dotfiles/blob/master/script/codespaces-post-start
# apt-get install -y \
#   tmux

# Install golang-petname utility to GOBIN
go install github.com/dustinkirkland/golang-petname/cmd/petname@latest

# Generate a unique petname for this machine instance
if ! [ -s ~/.petname ]
then
  $HOME/go/bin/petname > ~/.petname
  echo "Generated petname: $(cat ~/.petname)"
fi

$SELFDIR/update-vscode-settings.sh

# Install tmux config
cp $SELFDIR/.tmux.conf ~/

# Add stuff to .bashrc
if ! grep -q hashtagchris ~/.bashrc
then
  echo >> ~/.bashrc
  cat $SELFDIR/.bashrc-additions >> ~/.bashrc
fi
