#!/bin/sh

SELFDIR=$(cd "$(dirname "$0")"; pwd)

# Debugging
echo "" >> /tmp/my-log
echo "invoke: $0" >> /tmp/my-log
echo "pwd: `pwd`" >> /tmp/my-log
echo "SELFDIR: $SELFDIR" >> /tmp/my-log

# Install golang-petname utility to GOBIN
go install github.com/dustinkirkland/golang-petname/cmd/petname@latest

# Generate a unique petname for this machine instance
# Another option is to use $CODESPACE_NAME as a default machine name
if [[ ! -f "${HOME}/.machine_name" ]]; then
  $HOME/go/bin/petname > ~/.machine_name
fi

# Install tmux config
cp $SELFDIR/.tmux.conf ~/

# Add stuff to .bashrc
# echo >> ~/.bashrc
# cat $SELFDIR/.bashrc-additions >> ~/.bashrc
