#!/bin/sh

echo "" >> /tmp/my-log
echo "invoke: $0" >> /tmp/my-log
echo "pwd: `pwd`" >> /tmp/my-log

cat >> ~/.bashrc << HERE

# hashtagchris/dotfile additions
export PATH=\$PATH:/workspaces/github/bin
HERE
